os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - jq
    - libcap-dev
language: node_js
node_js:
- "6"
osx_image: xcode8
install:
- true
script:
- ./build.sh
notifications:
  email: false
